// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDipNnGSP8n5zGEhFecDbBTcyAXWQQN7pg',
    appId: '1:686674403698:web:85799bc3b9a0cc72bd7deb',
    messagingSenderId: '686674403698',
    projectId: 'free-yourself-app-830fa',
    authDomain: 'free-yourself-app-830fa.firebaseapp.com',
    storageBucket: 'free-yourself-app-830fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNDHMls4UeHHiZv70oGyRJa2kVoJah434',
    appId: '1:686674403698:android:159911fdea3d8c6cbd7deb',
    messagingSenderId: '686674403698',
    projectId: 'free-yourself-app-830fa',
    storageBucket: 'free-yourself-app-830fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5KTzCgFHx4yLJAiNOSj3GGDQin1tGuU8',
    appId: '1:686674403698:ios:7899278e4ea10abfbd7deb',
    messagingSenderId: '686674403698',
    projectId: 'free-yourself-app-830fa',
    storageBucket: 'free-yourself-app-830fa.appspot.com',
    iosBundleId: 'com.example.freeYourselfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5KTzCgFHx4yLJAiNOSj3GGDQin1tGuU8',
    appId: '1:686674403698:ios:816000f1282af697bd7deb',
    messagingSenderId: '686674403698',
    projectId: 'free-yourself-app-830fa',
    storageBucket: 'free-yourself-app-830fa.appspot.com',
    iosBundleId: 'com.example.freeYourselfApp.RunnerTests',
  );
}
